// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:70d3fbef-9ea5-44ca-894d-bec15034c115",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VvaOhobD1",
    "aws_user_pools_web_client_id": "257dpg7bmbto3o1r20j9hqmcj9",
    "oauth": {}
};


export default awsmobile;
