name: Greet Everybody
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: echo "The time was ${{ steps.hello.outputs.time }}"
